=== xmlportletfactory/xmlportletfactory/Resources/xml/7.0_samples/xmlportletfactory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.xmlportletfactory.org/xml/xmlportletfactory" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.xmlportletfactory.org/xml/xmlportletfactory" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="definition">
		<xs:complexType>
			<xs:all>
				<xs:element name="commonData">
					<xs:complexType>
						<xs:all>
							<xs:element name="client" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="3"/>
										<xs:whiteSpace value="collapse"/>
										<xs:pattern value="[A-Za-z0-9\.]*"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="projectName" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="3"/>
										<xs:whiteSpace value="collapse"/>
										<xs:pattern value="[A-Za-z]*"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="version" type="xs:short" minOccurs="0"/>
							<xs:element name="bbddApplicationsData" minOccurs="0" nillable="true">
								<xs:complexType>
									<xs:all>
										<xs:element name="driver" nillable="false">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="3"/>
													<xs:whiteSpace value="collapse"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="url" nillable="false">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="3"/>
													<xs:whiteSpace value="collapse"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="username" type="xs:string" nillable="true"/>
										<xs:element name="password" type="xs:string"/>
										<xs:element name="maxactive" type="xs:unsignedShort" default="20" nillable="false"/>
										<xs:element name="poolable" type="xs:boolean" default="true"/>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="applications">
					<xs:complexType>
						<xs:sequence maxOccurs="255">
							<xs:element name="application">
								<xs:complexType>
									<xs:sequence>										
										<xs:element name="classDef" nillable="false" maxOccurs="1">
											<xs:complexType>
												<xs:all>
													<xs:element name="name" nillable="false">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="3"/>
																<xs:whiteSpace value="collapse"/>
																<xs:pattern value="[A-Za-z0-9]*"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="title" nillable="false">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="3"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="mode" nillable="true" minOccurs="0">
														<xs:complexType>
															<xs:all>
																<xs:element name="add" type="xs:boolean" default="true" nillable="false"/>
																<xs:element name="delete" type="xs:boolean" default="true"/>
																<xs:element name="modify" type="xs:boolean" default="true"/>
																<xs:element name="browse" type="xs:boolean" default="true"/>
															</xs:all>
														</xs:complexType>
													</xs:element>
													<xs:element name="generatePortlet" type="xs:boolean" default="true" minOccurs="0"/>
													<xs:element name="restrictBy" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="companyId" type="xs:boolean" default="true" minOccurs="0"/>
																<xs:element name="groupId" type="xs:boolean" default="false" minOccurs="0"/>
																<xs:element name="userId" type="xs:boolean" default="false" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="workflow" type="xs:boolean" default="false" minOccurs="0" maxOccurs="1"/>
													<xs:element name="trash" type="xs:boolean" default="false" minOccurs="0" maxOccurs="1"/>
													<xs:element name="generateActivity" type="xs:boolean" default="false" minOccurs="0" maxOccurs="1"/>
													<xs:element name="showInControlPanel" type="xs:boolean" default="false" minOccurs="0" maxOccurs="1"/>
													<xs:element name="asset" nillable="true" minOccurs="0">
														<xs:complexType>
															<xs:all>
																<xs:element name="assetTitleFieldName" nillable="false" default="title"  minOccurs="1" maxOccurs="1">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:minLength value="3"/>
																			<xs:whiteSpace value="collapse"/>
																			<xs:pattern value="[A-Za-z0-9]*" />
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="assetSummaryFieldName" nillable="false" default="description" minOccurs="1" maxOccurs="1">
																	<xs:simpleType>
																		<xs:restriction base="xs:string" >
																			<xs:minLength value="3"/>
																			<xs:whiteSpace value="collapse"/>
																			<xs:pattern value="[A-Za-z0-9]*"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="fullContentFieldName" nillable="false" default="description" minOccurs="1" maxOccurs="1">
																	<xs:simpleType>
																		<xs:restriction base="xs:string" >
																			<xs:minLength value="3"/>
																			<xs:whiteSpace value="collapse"/>
																			<xs:pattern value="[A-Za-z0-9]*"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="discussion" type="xs:boolean" default="false" minOccurs="1" maxOccurs="1"/>
																<xs:element name="ratings" type="xs:boolean" default="false" minOccurs="1" maxOccurs="1"/>
																<xs:element name="categories" type="xs:boolean" default="false" minOccurs="1" maxOccurs="1"/>
																<xs:element name="tags" type="xs:boolean" default="false" minOccurs="1" maxOccurs="1"/>
																<xs:element name="relatedAssets" type="xs:boolean" default="false" minOccurs="1" maxOccurs="1"/>
															</xs:all>
														</xs:complexType>
													</xs:element>
												</xs:all>
											</xs:complexType>
										</xs:element>
										<xs:element name="fileDef" nillable="false" maxOccurs="1">
											<xs:complexType>
												<xs:all>
													<xs:element name="name" nillable="false">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="3"/>
																<xs:whiteSpace value="collapse"/>
																<xs:pattern value="[a-zA-Z0-9_]*"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="fields">
														<xs:complexType>
															<xs:sequence maxOccurs="255">
																<xs:element name="field">
																	<xs:complexType>
																		<xs:all>
																			<xs:element name="name" nillable="false">
																				<xs:simpleType>
																					<xs:restriction base="xs:string">
																						<xs:minLength value="3"/>
																						<xs:whiteSpace value="collapse"/>
																						<xs:pattern value="[a-zA-Z0-9_]*"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>
																			<xs:element name="title" nillable="false">
																				<xs:simpleType>
																					<xs:restriction base="xs:string">
																						<xs:minLength value="1"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>
																			<xs:element name="type">
																				<xs:complexType>
																					<xs:choice>
																						<xs:element name="calculated">
																							<xs:simpleType>
																								<xs:restriction base="xs:string">
																									<xs:minLength value="3"/>
																									<xs:whiteSpace value="collapse"/>
																									<xs:pattern value="([a-zA-Z0-9_*+-/()\s])*"/>
																								</xs:restriction>
																							</xs:simpleType>
																						</xs:element>
																						<xs:element name="int">
																							<xs:complexType>
																								<xs:all>
																									<xs:element name="length" type="xs:unsignedShort" nillable="false"/>
																									<xs:element name="signed" type="xs:boolean" default="false"/>
																									<xs:element name="zerofill" type="xs:boolean" default="true"  minOccurs="0"/>
																									<xs:element name="nullable" type="xs:boolean" default="false"/>
																									<xs:element name="regexp" type="xs:string" minOccurs="0" />
																									<xs:element name="order" type="xs:boolean"  default="false" minOccurs="0" />
																									<xs:element name="unique" type="xs:boolean"  default="false" minOccurs="0" />
																								</xs:all>
																							</xs:complexType>
																						</xs:element>
																						<xs:element name="long">
																							<xs:complexType>
																								<xs:all>
																									<xs:element name="length" type="xs:unsignedShort" nillable="false"/>
																									<xs:element name="signed" type="xs:boolean" default="false"/>
																									<xs:element name="nullable" type="xs:boolean" default="false"/>
																									<xs:element name="regexp" type="xs:string" minOccurs="0" />
																									<xs:element name="order" type="xs:boolean"  default="false" minOccurs="0" />
																									<xs:element name="unique" type="xs:boolean"  default="false" minOccurs="0" />
																								</xs:all>
																							</xs:complexType>
																						</xs:element>
																						<xs:element name="numeric">
																							<xs:complexType>
																								<xs:all>
																									<xs:element name="length" type="xs:unsignedShort"/>
																									<xs:element name="decimals" type="xs:unsignedShort"/>
																									<xs:element name="regexp" type="xs:string" minOccurs="0" />
																									<xs:element name="order" type="xs:boolean"  default="false" minOccurs="0" />
																									<xs:element name="unique" type="xs:boolean"  default="false" minOccurs="0" />
																								</xs:all>
																							</xs:complexType>
																						</xs:element>
																						<xs:element name="float">
																							<xs:complexType>
																								<xs:all>
																									<xs:element name="length" type="xs:unsignedShort"/>
																									<xs:element name="decimals" type="xs:unsignedShort"/>
																									<xs:element name="regexp" type="xs:string" minOccurs="0" />
																									<xs:element name="order" type="xs:boolean"  default="false" minOccurs="0" />
																									<xs:element name="unique" type="xs:boolean"  default="false" minOccurs="0" />
																								</xs:all>
																							</xs:complexType>
																						</xs:element>
																						<xs:element name="date">
																							<xs:complexType>
																								<xs:all minOccurs="0">
																									<xs:element name="order" type="xs:boolean" default="false"/>
																								</xs:all>
																							</xs:complexType>
																						</xs:element>
																						<xs:element name="datetime">
																							<xs:complexType>
																								<xs:all minOccurs="0">
																									<xs:element name="order" type="xs:boolean" default="false"/>
																								</xs:all>
																							</xs:complexType>
																						</xs:element>
																						<xs:element name="timestamp" type="xs:dateTime"/>
																						<xs:element name="enum">
																							<xs:complexType>
																								<xs:all>
																									<xs:element name="values" type="xs:string" default="'SI','NO'" nillable="false"/>
																									<xs:element name="default" type="xs:string" default="'SI'" nillable="false"/>
																								</xs:all>
																							</xs:complexType>
																						</xs:element>
																						<xs:element name="varchar">
																							<xs:complexType>
																								<xs:all>
																									<xs:element name="length" type="xs:unsignedShort"/>
																									<xs:element name="regexp" type="xs:string" minOccurs="0" />
																									<xs:element name="order" type="xs:string" minOccurs="0" />
																									<xs:element name="unique" type="xs:boolean"  default="false" minOccurs="0" />
																									<xs:element name="filter" type="xs:string" minOccurs="0" />
																								</xs:all>
																							</xs:complexType>
																						</xs:element>
																						<xs:element name="text"/>
																						<xs:element name="richtext"/>
																						<xs:element name="boolean"/>
																						<xs:element name="image"/>
																						<xs:element name="document"/>
																						<xs:element name="documentlibrary"/>
																					</xs:choice>
																				</xs:complexType>
																			</xs:element>
																			<xs:element name="showFieldInView" type="xs:boolean" default="true"/>
																			<xs:element name="required" type="xs:boolean" default="false" minOccurs="0"/>
																			<xs:element name="validation" minOccurs="0">
																				<xs:complexType>
																					<xs:all>
																						<xs:element name="className" type="xs:Name" minOccurs="1"  maxOccurs="1"/>
																						<xs:element name="fieldName" type="xs:Name" minOccurs="1"  maxOccurs="1"/>
																						<xs:element name="orderByField" type="xs:Name" minOccurs="1"  maxOccurs="1"/>
																						<xs:element name="depends"  minOccurs="0"  maxOccurs="1">
																							<xs:complexType>
																								<xs:all>
																									<xs:element name="localFieldName" nillable="false"  minOccurs="1"  maxOccurs="1">
																										<xs:simpleType>
																											<xs:restriction base="xs:string">
																												<xs:minLength value="3"/>
																												<xs:whiteSpace value="collapse"/>
																												<xs:pattern value="[a-zA-Z0-9_]*"/>
																											</xs:restriction>
																										</xs:simpleType>
																									</xs:element>
																									<xs:element name="againstFieldName" nillable="false" minOccurs="1" maxOccurs="1">
																										<xs:simpleType>
																											<xs:restriction base="xs:string">
																												<xs:minLength value="3"/>
																												<xs:whiteSpace value="collapse"/>
																												<xs:pattern value="[a-zA-Z0-9_]*"/>
																											</xs:restriction>
																										</xs:simpleType>
																									</xs:element>
																								</xs:all>
																							</xs:complexType>
																						</xs:element>
																					</xs:all>
																				</xs:complexType>
																			</xs:element>
																		</xs:all>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="autoKey" type="xs:boolean" default="true" nillable="true" minOccurs="0"/>
													<xs:element name="poolable" type="xs:boolean" default="true" nillable="true" minOccurs="0"/>
												</xs:all>
											</xs:complexType>
										</xs:element>
										<xs:element name="detailFiles" minOccurs="0">
											<xs:complexType>
												<xs:sequence maxOccurs="255">
													<xs:element name="detailFile"  nillable="true" minOccurs="1">
														<xs:complexType>
															<xs:all>
																<xs:element name="detailFileClassName" nillable="false">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:pattern value="[a-zA-Z0-9]*"/>
																			<xs:whiteSpace value="collapse"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="connectionFieldName" nillable="false">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:pattern value="[a-zA-Z0-9_]*"/>
																			<xs:whiteSpace value="collapse"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="connectionTitle" nillable="false"> 
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:pattern value="(.)+"/>
																			<xs:whiteSpace value="replace"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
															</xs:all>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="bbddFileData" minOccurs="0">
											<xs:complexType>
												<xs:all>
													<xs:element name="driver" nillable="false">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="3"/>
																<xs:whiteSpace value="collapse"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="url" nillable="false">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="3"/>
																<xs:whiteSpace value="collapse"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="username" type="xs:string" nillable="true"/>
													<xs:element name="password" type="xs:string"/>
													<xs:element name="maxactive" type="xs:unsignedShort" default="20" nillable="false"/>
												</xs:all>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xmlportletfactory/xmlportletfactory/Resources/xml/7.0_samples/SchoolCoursesExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<definition xmlns="http://www.xmlportletfactory.org/xml/xmlportletfactory" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xmlportletfactory.org/xml/xmlportletfactory xmlportletfactory.xsd">
	<commonData>
        <client>org.xmlpf</client>
		<projectName>SchoolCoursesSample</projectName>
        <version>1</version>
        
	</commonData>
	<applications>
		<application>
			<classDef>
				<showInControlPanel>true</showInControlPanel>
				<name>Course</name>
				<title>Course</title>
				<mode>
					<add>true</add>
					<delete>true</delete>
					<modify>true</modify>
					<browse>true</browse>
				</mode>
			</classDef>
			<fileDef>
				<name>course</name>
				<fields>
					<field>
						<name>courseId</name>
						<title>Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>courseName</name>
						<title>Course Name</title>
						<type>
							<varchar>
								<length>30</length>	
								<filter>true</filter>
								<order>true</order>
							</varchar>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>courseActive</name>
						<title>Is Active</title>
						<type>
							<boolean></boolean>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>false</required>
					</field>
				</fields>
			</fileDef>
			<detailFiles>
				<detailFile>
					<connectionFieldName>courseId</connectionFieldName>
					<connectionTitle>Student - Course</connectionTitle>
					<detailFileClassName>Student</detailFileClassName>
				</detailFile>
				<detailFile>
					<connectionFieldName>courseId</connectionFieldName>
					<connectionTitle>Holidays - Course</connectionTitle>
					<detailFileClassName>Holiday</detailFileClassName>
				</detailFile>
				<detailFile>
					<connectionFieldName>courseId</connectionFieldName>
					<connectionTitle>CourseSubjects - Course</connectionTitle>
					<detailFileClassName>CourseSubjects</detailFileClassName>
				</detailFile>
			</detailFiles>			
		</application>

		<application>
			<classDef>
				<showInControlPanel>true</showInControlPanel>
				<name>Student</name>
				<title>Student</title>
				<mode>
					<add>true</add>
					<delete>true</delete>
					<modify>true</modify>
					<browse>true</browse>
				</mode>
			</classDef>
			<fileDef>
				<name>student</name>
				<fields>
					<field>
						<name>studentId</name>
						<title>Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>courseId</name>
						<title>Course Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<showFieldInView>false</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>studentName</name>
						<title>Name</title>
						<type>
							<varchar>
								<length>30</length>	
								<filter>true</filter>
								<order>true</order>
							</varchar>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>classroomId</name>
						<title>Classroom</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<showFieldInView>false</showFieldInView>
						<required>true</required>
						<validation>
							<className>Classrooms</className>
							<fieldName>classroomId</fieldName>
							<orderByField>classroomName</orderByField>
						</validation>            
					</field>
					<field>
						<name>studentPhoto</name>
						<title>Photo</title>
						<type>
							<document></document>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>false</required>
					</field>
				</fields>
			</fileDef>
			<detailFiles>
				<detailFile>
					<connectionFieldName>studentId</connectionFieldName>
					<connectionTitle>Comments - Student</connectionTitle>
					<detailFileClassName>Comments</detailFileClassName>
				</detailFile>
			</detailFiles>			
		</application>
		
		<application>
			<classDef>
				<showInControlPanel>true</showInControlPanel>
				<name>Classroom</name>
				<title>Classroom</title>
				<mode>
					<add>true</add>
					<delete>true</delete>
					<modify>true</modify>
					<browse>true</browse>
				</mode>
			</classDef>
			<fileDef>
				<name>classroom</name>
				<fields>
					<field>
						<name>classroomId</name>
						<title>Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>classroomName</name>
						<title>Name</title>
						<type>
							<varchar>
								<length>30</length>	
								<filter>true</filter>
								<order>true</order>
							</varchar>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>true</required>
					</field>
				</fields>
			</fileDef>
		</application>

		<application>
			<classDef>
				<showInControlPanel>true</showInControlPanel>
				<name>StudentComment</name>
				<title>Student Comment</title>
				<mode>
					<add>true</add>
					<delete>true</delete>
					<modify>true</modify>
					<browse>true</browse>
				</mode>
			</classDef>
			<fileDef>
				<name>comment</name>
				<fields>
					<field>
						<name>commentId</name>
						<title>Comment Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>studentId</name>
						<title>Student Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<showFieldInView>false</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>comment</name>
						<title>Comment</title>
						<type>
							<text></text>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>false</required>
					</field>
				</fields>
			</fileDef>
		</application>		
		
		<application>
			<classDef>
				<showInControlPanel>true</showInControlPanel>
				<name>CourseSubject</name>
				<title>Course Subject</title>
				<mode>
					<add>true</add>
					<delete>true</delete>
					<modify>true</modify>
					<browse>true</browse>
				</mode>
			</classDef>
			<fileDef>
				<name>courseSubject</name>
				<fields>
					<field>
						<name>courseSubjectId</name>
						<title>Course Subject Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<showFieldInView>true</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>courseId</name>
						<title>Course Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<showFieldInView>false</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>subjectId</name>
						<title>Subject Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<validation>
							<className>Subjects</className>
							<fieldName>subjectId</fieldName>
							<orderByField>subjectName</orderByField>
						</validation>
						<showFieldInView>true</showFieldInView>
						<required>true</required>
					</field>
					<field>
						<name>teacherId</name>
						<title>Teacher Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
								<nullable>false</nullable>
								<order>true</order>
							</long>
						</type>
						<validation>
							<className>Teachers</className>
							<fieldName>teacherId</fieldName>
							<orderByField>teacherName</orderByField>
						</validation>
						<showFieldInView>true</showFieldInView>
						<required>true</required>
					</field>
				</fields>
			</fileDef>
		</application>
		
		<application>
			<classDef>
				<showInControlPanel>true</showInControlPanel>
				<name>Subject</name>
				<title>Subject</title>
				<mode>
					<add>true</add>
					<delete>true</delete>
					<modify>true</modify>
					<browse>true</browse>
				</mode>
			</classDef>
			<fileDef>
				<name>subject</name>
				<fields>
					<field>
						<name>subjectId</name>
						<title>Subject Id</title>
						<type>
							<long>
								<length>5</length>
								<signed>false</signed>
